### ISSUE TITLE
2.16.0beta4 ACRA crash report umbrella issue

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#14047]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

These are taken from ACRA, go there and filter reports by `2.16.0beta4`, open each report, close duplicates, close things that are "normal" (like sync exceptions for bad passwords) and you get these

### Expected behaviour

No crashing :-)

### Actual behaviour

- Sched V2 appears to have a problem with concurrent modification, something about the way the data structure is currently setup + used is wrong and leading to both:
  -  [x] #14066
- [x] #14068
- A couple of ways to have no write access to the legacy external storage, even though these are on new devices (API33)
  - [ ] migration failure? https://ankidroid.org/acra/app/1/bug/56825/report/37303570-f44e-4b1c-b562-3d2e397dea73
  - [ ] *lower priority - `full` version user*: new user setup, but tried to create directory in legacy location? https://ankidroid.org/acra/app/1/bug/56630/report/37bcaaf4-cc63-4829-8ed2-1b8b634df602
- [x] Media check dialog apparently gets some null media check result on it's callback and crashes, a couple reports https://ankidroid.org/acra/app/1/bug/50298/report/512c3b37-3cf3-499a-b054-ece901b318a1
- [ ] *no priority for 2.16* - new backend still experimental - SchedV3/new-backend concurrent card modification / user attempted to answer a card and was unable: https://ankidroid.org/acra/app/1/bug/56628/report/1fa0b88b-3b66-48e2-b2da-592d9f934b14

### Debug info

```text
2.16.0beta4 as delivered from Play store
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
> new user setup, but tried to create directory in legacy location? https://ankidroid.org/acra/app/1/bug/56630/report/37bcaaf4-cc63-4829-8ed2-1b8b634df602

`full` user. Currently, a little less priority than the issues with the `play` version

**Comment by mikehardy** [comment]
Good point re: the full user, I agree, I annotated that entry as lower priority and added the information. Good catch, I forgot about our different flavors!
