### ISSUE TITLE
[Bug] "Share feature usage" on by default, but FDroid doesn't report "tracking" antifeature

### ISSUE THREAD

**Issue by sudomain** [ankidroid/Anki-Android#14386]
###### Reproduction Steps

1. I recently reinstalled AnkiDroid due to #14216 
2. I went through the settings and noticed the share feature usage setting is enabled by default.
3. I'm personally fine with sharing which features I use with AnkiDroid, but some people would not. Apps that report user activity by default can be listed on FDroid, but need to include the [tracking anti-feature](https://f-droid.org/docs/Anti-Features/#Tracking).

###### Expected Result
Either share feature usage should be off by default for the FDroid build or the AnkiDroid FDroid listing should include the tracking anti-feature. If the latter, AnkiDroid (like other apps) can utilize their app description to explain why they have certain anti-features. Presumably it has the "non-free network services" anti-feature due to its use of Ankiweb?

###### Actual Result
Report user activity is on by default and there's no tracking anti-feature

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.16.4 (67fd45a351c44c46c844aa35a402b98a2a487f68)

Android Version = 11

ProductFlavor = full

Manufacturer = Google

Model = Pixel 2

Hardware = walleye

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Pixel 2 Build/RP1A.201005.004.A1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Mobile Safari/537.36

ACRA UUID = f4019fd8-34de-4209-ae57-63c3eb0e75ee

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
This should NOT be on by default

Thank you for the report!

**Comment by mikehardy** [comment]
Most unfortunate this was set the wrong way as a default - definitely not then intention.

At least from a practical impact point of view our analytics property isn't configured right now since google switched to "GA4" so *no one* was tracked and currently no tracking is happening even if it was enabled, but that's a weak defense and the default for this and anything else that causes any network interaction at all, including but not limited to analytics, needs to be off to match our perspective of user respect

Thanks @sudomain for noticing this and @RobozinhoD for the fix, really appreciated.

**Comment by david-allison** [comment]
For posterity, also see discussion on
* https://github.com/ankidroid/ankidroiddocs/pull/115
